// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHDb66g353sE4YQ8X9E4eLEQJKdpR1hVQ',
    appId: '1:1020283165783:web:77b87c11229ef408039712',
    messagingSenderId: '1020283165783',
    projectId: 'app-dev-b00e6',
    authDomain: 'app-dev-b00e6.firebaseapp.com',
    storageBucket: 'app-dev-b00e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0Ngx1jrNg71-8za1dtsptRHGrXa0MmQ',
    appId: '1:1020283165783:android:1c8696b7995b382c039712',
    messagingSenderId: '1020283165783',
    projectId: 'app-dev-b00e6',
    storageBucket: 'app-dev-b00e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOuU8AIP5guHkCsyWnV3v_Lutn9ppF02o',
    appId: '1:1020283165783:ios:991c6fc568483d92039712',
    messagingSenderId: '1020283165783',
    projectId: 'app-dev-b00e6',
    storageBucket: 'app-dev-b00e6.firebasestorage.app',
    iosBundleId: 'com.example.appDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOuU8AIP5guHkCsyWnV3v_Lutn9ppF02o',
    appId: '1:1020283165783:ios:991c6fc568483d92039712',
    messagingSenderId: '1020283165783',
    projectId: 'app-dev-b00e6',
    storageBucket: 'app-dev-b00e6.firebasestorage.app',
    iosBundleId: 'com.example.appDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHDb66g353sE4YQ8X9E4eLEQJKdpR1hVQ',
    appId: '1:1020283165783:web:676ce4528b46a316039712',
    messagingSenderId: '1020283165783',
    projectId: 'app-dev-b00e6',
    authDomain: 'app-dev-b00e6.firebaseapp.com',
    storageBucket: 'app-dev-b00e6.firebasestorage.app',
  );
}
